# PROFILES
# dev | test | prod
spring:
    profiles:
        active: dev
---
#                  dev 开发环境
# --------------------------------------------------
spring:
    profiles: dev
    redis:
        host: 127.0.0.1
        port: 6379
        password: isiagvK6TQqCt84
        timeout: 120
        database: 11

# LOGGING
logging:
    config: classpath:logback-spring.xml

server:
    port: 8088

datasource:
    master:
        url: jdbc:mysql://aws-dev.cbqdef72uoed.us-west-2.rds.amazonaws.com:3306/sbs?useUnicode=true&characterEncoding=utf-8&useSSL=false
        username: miaoxg
        password: miaoxg2002
