package io.github.miaoxinguo.sbs.dao;

import io.github.miaoxinguo.sbs.entity.User;
import io.github.miaoxinguo.sbs.modal.PageableRepository;
import io.github.miaoxinguo.sbs.qo.PageQueryObject;
import java.util.List;

public interface UserMapper extends PageableRepository {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbg.generated
     */
    int insert(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbg.generated
     */
    User selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbg.generated
     */
    List<User> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbg.generated
     */
    int updateNotEmptyByPrimaryKey(User record);
}